### ISSUE TITLE
How to train a new dataset with the model?

### ISSUE THREAD

**Issue by bharathreddy1997** [suragnair/seqGAN#13]
hello, can you tell me how to train a custom dataset with the model?

**Comment by suragnair** [comment]
Hello. Does #5 answer your question?

**Comment by bharathreddy1997** [comment]
How do you create a vocabulary file ? i am unable to figure how to index a token ?

**Comment by suragnair** [comment]
You will need to make a vocabulary. The entries of samples is then simply the index of tokens in the sentence.
