### ISSUE TITLE
How to see the orcale data

### ISSUE THREAD

**Issue by FreeRotate** [suragnair/seqGAN#16]
Hello sir, I'm confused about the oracle_samples.trc and oracle_EMBDIM32_HIDDENDIM32_VOCAB5000_MAXSEQLEN20.trc. 
How to check the data in the two file?

**Comment by FreeRotate** [comment]
oracle_samples.trc is real data with encode as numbers, and type is tensor.
oracle_EMBDIM32_HIDDENDIM32_VOCAB5000_MAXSEQLEN20.trc is a Generator model.
Is that right?

**Comment by suragnair** [comment]
https://github.com/suragnair/seqGAN/blob/ae8ffcd54977bd9ee177994c751f86d34f5f7aa3/main.py#L30-L33

You can use `torch.load` to inspect them
