### ISSUE TITLE
why batchwise_sample?

### ISSUE THREAD

**Issue by skpig** [suragnair/seqGAN#18]
Thanks a lot for your code. It really helps me to learn GAN. But here is a question about your implementation. Why implement `batchwise_sample(gen, num_samples, batch_size)` instead of just using `gen.sample(num_samples)` ?
https://github.com/suragnair/seqGAN/blob/ae8ffcd54977bd9ee177994c751f86d34f5f7aa3/helpers.py#L66-L76

**Comment by suragnair** [comment]
Hi I think it's because you often want to draw a lot of samples but can't do it in one call to `gen.sample` as it won't fit in GPU memory. So you do it `batch_size` at a time.
