### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by cbsudux** [suragnair/seqGAN#2]
Hi, really good work. I am facing issues with training ( Tesla K80 ).

How long did it take for you to train?

**Comment by suragnair** [comment]
It's been a while so I don't quite remember exactly, but I think it was around 1 day on my laptop (no GPU). I'm sure you've done this, but just double checking- did you set CUDA to true in main.py?

**Comment by cbsudux** [comment]
Yes I did. I solved the issue by reinstalling pytorch though. Thanks anyways!
