### ISSUE TITLE
How to provide you own positive samples? 

### ISSUE THREAD

**Issue by Houd1ny** [suragnair/seqGAN#5]

**Comment by suragnair** [comment]
Oracle sample is simply a matrix of length `NUM_EXAMPLES x MAX_SENTENCE_LENGTH`. So you can  pass in a similar matrix as positive examples. If you have access to the oracle model, you can pass that in as well here:

https://github.com/suragnair/seqGAN/blob/725686d9b1a58dbf0b9215812374e75e1b9ca982/main.py#L141

**Comment by Houd1ny** [comment]
How you encode each character?

**Comment by suragnair** [comment]
You will need to make a vocabulary. The entries of oracle samples is then simply the index of tokens in the sentence.

**Comment by Houd1ny** [comment]
Right now everything is clear!
Many thanks to you

**Comment by awarebayes** [comment]
That's kinda corny. Is it possible to use it with embeddings?
