### ISSUE TITLE
SeqGAN for continuous data

### ISSUE THREAD

**Issue by dokato** [suragnair/seqGAN#8]
Hi @suragnair, thanks for sharing your code. I wonder if you think that should be straightforward to adjust your code to predict real-valued samples, instead of discrete ones. Or you see some issues with that I'm not aware of?

For now what comes to my mind is to get rid of Embedding layer and change loss from `NLLoss` to - let's say - `KLDivLoss`.

Do you think it's doable?

**Comment by suragnair** [comment]
Hi, any specific reason why you want to use seqGAN for continuous data? There are many other alternatives that are available (e.g. WGAN)

**Comment by dokato** [comment]
So I was thinking about using it as a baseline to weather predictions. For instance, generating patterns of temperatures among different cities in time. WGAN offers just different measure of probability distributions, but still has fixed windows size of generated data. I'm aiming for a generator that could generate (theoretically) an infinite number of samples. Looks like seqGAN is perfect for my purposes, but rather than having a dictionary with fixed labels I'd rather have a continuous spectrum of values.

**Comment by suragnair** [comment]
The bulk of the work on GANs focuses on images, which are modeled as continuous variables. I think it's worth checking out some of the main work starting with the paper by Goodfellow et al. seqGANs are, in a way, a hack to get GANs to work for discrete variables, and so to adapt seqGANs for continuous data would almost be akin to hacking a hack.

**Comment by dokato** [comment]
Thanks for clarification. I think what troubles me is that the naming here. I thought that sequence refers to any sequential data, no matter discrete or real. But indeed, in the original Luntao Yu paper they refer to the problem with discrete outputs from the generative model are difficult to pass the gradient update from the discriminative model to the generative model.
However, as you have noticed WGANs etc. are used to images mainly, so that you have a fixed output size. What attracted me to this solution is LSTM structure that generates long range sets.

**Comment by suragnair** [comment]
Oh I see. It seems this might match your needs better: https://arxiv.org/abs/1611.09904. An implementation here: https://github.com/olofmogren/c-rnn-gan. I would also recommend training simple LSTMs at first using log-likelihood, and perhaps a Variational Autoencoder. Bunch of stuff here: https://medium.com/cindicator/music-generation-with-neural-networks-gan-of-the-week-b66d01e28200.

**Comment by dokato** [comment]
Thank you, cool stuff! Exactly what I need. And once again, nice work with this seqGAN implementation.
