### ISSUE TITLE
Problem with new oracle data

### ISSUE THREAD

**Issue by k-eak** [suragnair/seqGAN#9]
Hi,

I was able to achieve the same results when I used your oracle data but when I try to generate new oracle data with oracle_init=True argument + helpers.batchwise_sample(), NLL doesn't seem to be improving. Here is an NLL plot (y-axis) after 50 epochs (x-axis)
![image](https://user-images.githubusercontent.com/17920084/63005212-eb7c2480-be30-11e9-8733-8086d7823327.png)

Do you have any suggestion for me?

**Comment by suragnair** [comment]
Hi, did you use `oracle_init=True` and then save the samples generated using `helpers.batchwise_sample()` and use them from training?
